package byps.test.api.ver;

/*
 * Serializer for byps.test.api.ver.BRequest_EvolveIF_sendEvolveToClient
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=0

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_714115141 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_714115141();
	
	public BSerializer_714115141() {
		super(714115141);
	}
	
	public BSerializer_714115141(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_EvolveIF_sendEvolveToClient obj = (BRequest_EvolveIF_sendEvolveToClient)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_EvolveIF_sendEvolveToClient()));
		
		return obj;
	}
	
}
