package byps.ureq;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_BUtilityRequests_cancelMessage extends BMethodRequest implements Serializable {

	public long messageId;
	
	public final static long serialVersionUID = 1828952285L;
	
	public int getRemoteId() { return 174367442; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final BUtilityRequestsAsync __byps__remoteT = (BUtilityRequestsAsync)__byps__remote;			
			BAsyncResultSendMethod<Object> __byps__outerResult = new BAsyncResultSendMethod<Object>(__byps__asyncResult, new BResult_19());			
			__byps__remoteT.cancelMessage(messageId, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[BUtilityRequests.cancelMessage(");
		s.append(messageId);
		s.append(")]");
		return s.toString();
	}
	
}
