package byps.ureq;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenServer DO NOT MODIFY.
 */

import byps.*;

@SuppressWarnings("all")
public class BServer_UtilityRequests extends BServer { 

	public static BServer_UtilityRequests createServer(BTransportFactory transportFactory) {
		return new BServer_UtilityRequests(transportFactory);
	}
	
	public static BServer_UtilityRequests createServerR(BTransport transport) {
		return new BServer_UtilityRequests(transport);
	}
	
	public BServer_UtilityRequests(BTransport transport) {
		super(transport, null);
	}
	
	public BServer_UtilityRequests(BTransportFactory transportFactory) {
		super(
			transportFactory.createServerTransport(),
			transportFactory.createClientR(
				BClient_UtilityRequests.createClientR(
					transportFactory.createClientTransport()
				)
			)
		);
	}
	
	public BServer_UtilityRequests addRemote(BSkeleton_UtilityRequests remoteSkeleton) {
		addRemote(363558736, remoteSkeleton);
		return this;
	}
	
}
