package byps.ureq;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface BUtilityRequestsAsync extends BRemote, 
	BUtilityRequests {
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void cancelMessage(long messageId) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void cancelMessage(long messageId, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public java.util.Map<java.lang.String,java.lang.String> testAdapter(java.lang.String functionName, java.util.Map<java.lang.String,java.lang.String> params) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void testAdapter(java.lang.String functionName, java.util.Map<java.lang.String,java.lang.String> params, final BAsyncResult<java.util.Map<java.lang.String,java.lang.String>> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public java.util.Map<java.lang.String,java.lang.String> execute(java.lang.String functionName, java.util.Map<java.lang.String,java.lang.String> params) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void execute(java.lang.String functionName, java.util.Map<java.lang.String,java.lang.String> params, final BAsyncResult<java.util.Map<java.lang.String,java.lang.String>> asyncResult) ;
	
	
}
