package byps.test.api.arr;

/*
 * Serializer for byps.test.api.arr.ArrayTypes4dim
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=10

// checkpoint byps.gen.j.GenSerStruct:304
@SuppressWarnings("all")
public class BSerializer_2004 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_2004();
	
	public BSerializer_2004() {
		super(2004);
	}
	
	public BSerializer_2004(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final ArrayTypes4dim obj = (ArrayTypes4dim)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.boolean4, false, byps.test.api.BSerializer_945713488.instance);
		bout.writeObj(obj.byte4, false, byps.test.api.BSerializer_1201775504.instance);
		bout.writeObj(obj.char4, false, byps.test.api.BSerializer_769021986.instance);
		bout.writeObj(obj.double4, false, byps.test.api.BSerializer_2087445849.instance);
		bout.writeObj(obj.float4, false, byps.test.api.BSerializer_1516687588.instance);
		bout.writeObj(obj.int4, false, byps.test.api.BSerializer_39910537.instance);
		bout.writeObj(obj.long4, false, byps.test.api.BSerializer_846419204.instance);
		bout.writeObj(obj.primitiveTypes4, false, byps.test.api.BSerializer_758319514.instance);
		bout.writeObj(obj.short4, false, byps.test.api.BSerializer_1859644668.instance);
		bout.writeObj(obj.string4, true, byps.test.api.BSerializer_588723219.instance);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final ArrayTypes4dim obj = (ArrayTypes4dim)(obj1 != null ? obj1 : bin.onObjectCreated(new ArrayTypes4dim()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.boolean4 = (boolean[][][][])bin.readObj(false, byps.test.api.BSerializer_945713488.instance);
		obj.byte4 = (byte[][][][])bin.readObj(false, byps.test.api.BSerializer_1201775504.instance);
		obj.char4 = (char[][][][])bin.readObj(false, byps.test.api.BSerializer_769021986.instance);
		obj.double4 = (double[][][][])bin.readObj(false, byps.test.api.BSerializer_2087445849.instance);
		obj.float4 = (float[][][][])bin.readObj(false, byps.test.api.BSerializer_1516687588.instance);
		obj.int4 = (int[][][][])bin.readObj(false, byps.test.api.BSerializer_39910537.instance);
		obj.long4 = (long[][][][])bin.readObj(false, byps.test.api.BSerializer_846419204.instance);
		obj.primitiveTypes4 = (byps.test.api.prim.PrimitiveTypes[][][][])bin.readObj(false, byps.test.api.BSerializer_758319514.instance);
		obj.short4 = (short[][][][])bin.readObj(false, byps.test.api.BSerializer_1859644668.instance);
		obj.string4 = (java.lang.String[][][][])bin.readObj(true, byps.test.api.BSerializer_588723219.instance);
		
		return obj;
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		final ArrayTypes4dim obj = (ArrayTypes4dim)(obj1);		
		bin.prepareForLazyLoading(obj.primitiveTypes4, byps.test.api.BSerializer_758319514.instance);
		
	}
	
}
