package com.wilutions.byps.test.api.inherit;

/*
 * Serializer for com.wilutions.byps.test.api.inherit.Class3
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import com.wilutions.byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=1

// checkpoint com.wilutions.byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_6003 extends com.wilutions.byps.test.api.inherit.BSerializer_6002 {
	
	public final static BSerializer instance = new BSerializer_6003();
	
	public BSerializer_6003() {
		super(6003);
	}
	
	public BSerializer_6003(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final Class3 obj = (Class3)obj1;		
		super.write(obj, bout1, version);		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putInt(obj.int3);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final Class3 obj = (Class3)(obj1 != null ? obj1 : bin.onObjectCreated(new Class3()));
		
		// Read base class members
		super.read(obj, bin, version);
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.int3 = bbuf.getInt();
		
		return obj;
	}
	
}
