package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1752158699 extends BMethodResult<java.util.List<int[]>> implements Serializable {

	
	public final static long serialVersionUID = 1912328929L;
	
}
