package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1218831438 extends BMethodResult<java.util.List<java.io.InputStream>> implements Serializable {

	
	public final static long serialVersionUID = 911793767L;
	
}
