package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1097919350 extends BMethodResult<java.util.Set<java.util.Date>> implements Serializable {

	
	public static final long serialVersionUID = 428832038L;
	
}
