package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;
import java.util.List;

/**
*/
@SuppressWarnings("all")
public final class BResult_2123584667 extends BMethodResult<java.util.List<java.lang.String>> implements Serializable {

	
	public final static long serialVersionUID = 253151806L;
	
}
