package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1972793385 extends BMethodResult<java.util.HashMap<java.lang.Double,java.lang.Byte>> implements Serializable {

	
	public static final long serialVersionUID = 1958357790L;
	
}
