package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;
import java.util.Map;

/**
*/
@SuppressWarnings({"all","deprecation","unchecked","rawtypes","cast","static","try","serial","this-escape"})
public final class BResult_1487265161 extends BMethodResult<java.util.Map<java.lang.Byte,java.lang.Double>> implements Serializable {

	
	public final static long serialVersionUID = 149769063L;
	
}
