package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;
import java.util.TreeSet;

/**
*/
@SuppressWarnings("all")
public final class BResult_936607009 extends BMethodResult<java.util.TreeSet<java.lang.Character>> implements Serializable {

	
	public final static long serialVersionUID = 968248604L;
	
}
