package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_39910537 extends BMethodResult<int[][][][]> implements Serializable {

	
	public static final long serialVersionUID = 245460547L;
	
}
