package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;
import java.util.Set;

/**
*/
@SuppressWarnings({"all","deprecation","unchecked","rawtypes","cast","static","try","serial","this-escape"})
public final class BResult_1888799711 extends BMethodResult<java.util.Set<java.lang.String>> implements Serializable {

	
	public final static long serialVersionUID = 2051074845L;
	
}
