package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1406124761 extends BMethodResult<java.util.Set<int[]>> implements Serializable {

	
	public final static long serialVersionUID = 2127200796L;
	
}
