package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;
import java.util.Map;

/**
*/
@SuppressWarnings("all")
public final class BResult_1831201218 extends BMethodResult<java.util.Map<java.lang.Integer,byps.test.api.prim.PrimitiveTypes>> implements Serializable {

	
	public final static long serialVersionUID = 50516327L;
	
}
