package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings({"all","deprecation","unchecked","rawtypes","cast","static","try","serial","this-escape"})
public final class BResult_945713488 extends BMethodResult<boolean[][][][]> implements Serializable {

	
	public final static long serialVersionUID = 1852992857L;
	
}
