package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_564008001 extends BMethodResult<byps.test.api.ver.EvolveIF> implements Serializable {

	
	public final static long serialVersionUID = 1405156912L;
	
}
