package byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_769021986 extends BMethodResult<char[][][][]> implements Serializable {

	
	public final static long serialVersionUID = 580900026L;
	
}
