/* USE THIS FILE ACCORDING TO THE COPYRIGHT RULES IN LICENSE.TXT WHICH IS PART OF THE SOURCE CODE PACKAGE */
#ifndef METHODREQUEST_HPP_
#define METHODREQUEST_HPP_

#include "BMethodRequest.h"

namespace byps {

}

#endif
