/* USE THIS FILE ACCORDING TO THE COPYRIGHT RULES IN LICENSE.TXT WHICH IS PART OF THE SOURCE CODE PACKAGE */
#ifndef BSERIALIZABLE_HPP_
#define BSERIALIZABLE_HPP_

#include "Byps.h"

namespace byps {

}

#endif /* BSERIALIZABLE_H_ */
