/* USE THIS FILE ACCORDING TO THE COPYRIGHT RULES IN LICENSE.TXT WHICH IS PART OF THE SOURCE CODE PACKAGE */
#ifndef BSYNCHRONIZED_H
#define BSYNCHRONIZED_H

#include "Byps.h"

namespace byps {

}

#endif // BSYNCHRONIZED_H
