package com.wilutions.byps.test.api.inherit;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import com.wilutions.byps.*;

// checkpoint com.wilutions.byps.gen.j.GenRemoteClassAsync:68
public interface BioLemonServiceAsync extends BRemote, 
	BioLemonService, 
	com.wilutions.byps.test.api.inherit.BioFruitServiceAsync, 
	com.wilutions.byps.test.api.inherit.LemonServiceAsync {
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:357
	public int useParing() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:401
	public void useParing(final BAsyncResult<Integer> asyncResult) ;
	
	
}
