package com.wilutions.byps.test.api.inherit;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import com.wilutions.byps.*;

// checkpoint com.wilutions.byps.gen.j.GenRemoteClassAsync:68
public interface PlantServiceAsync extends BRemote, 
	PlantService {
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:357
	public java.lang.String grow() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:401
	public void grow(final BAsyncResult<String> asyncResult) ;
	
	
}
