package byps.test.api.inherit;

/*
 * Serializer for byps.test.api.inherit.BStub_LemonService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_826877615 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_826877615();
	
	public JSerializer_826877615() {
		super(826877615);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_LemonService(transport);
	}
	
}
