package byps.test.api.inherit;

/*
 * Serializer for byps.test.api.inherit.BStub_BioFruitService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_612235846 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_612235846();
	
	public JSerializer_612235846() {
		super(612235846);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_BioFruitService(transport);
	}
	
}
