package byps.test.api.inherit;

/*
 * Serializer for byps.test.api.inherit.BRequest_PlantService_grow
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=0

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_695716901 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_695716901();
	
	public JSerializer_695716901() {
		super(695716901);
	}
	
	public JSerializer_695716901(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_PlantService_grow obj = (BRequest_PlantService_grow)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_PlantService_grow()));
		
		return obj;
	}
	
}
