package byps.test.api.inherit;

/*
 * Serializer for byps.test.api.inherit.BStub_PlantService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1954605928 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1954605928();
	
	public JSerializer_1954605928() {
		super(1954605928);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_PlantService(transport);
	}
	
}
