package byps.test.api.inherit;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteProxy DO NOT MODIFY.
 */

import byps.*;

/**
 * This class provides a proxy implementation of the interface LemonService.
 */
@SuppressWarnings("all")
public class BProxy_LemonService extends BSkeleton_LemonService implements LemonServiceAsync {
	
	public static final long serialVersionUID = 605543968L;
	
	protected final byps.test.api.inherit.LemonServiceAsync forwardTo;
	
	public BProxy_LemonService(LemonServiceAsync forwardTo) {
		this.forwardTo = forwardTo;
	}
	
	public BProxy_LemonService(BTransport transport) {
		this(new BForward_LemonService(transport));
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public java.lang.String pick(byps.test.api.auth.SessionInfo sess, java.lang.String fromTree) throws RemoteException{
	  return forwardTo.pick(sess, fromTree);
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void pick(byps.test.api.auth.SessionInfo sess, java.lang.String fromTree, final BAsyncResult<String> asyncResult) {
	  forwardTo.pick(sess, fromTree, asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public java.lang.String squeeze() throws RemoteException{
	  return forwardTo.squeeze();
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void squeeze(final BAsyncResult<String> asyncResult) {
	  forwardTo.squeeze(asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public java.lang.String grow() throws RemoteException{
	  return forwardTo.grow();
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void grow(final BAsyncResult<String> asyncResult) {
	  forwardTo.grow(asyncResult);
	}
	
	
}
