package byps.test.api.inherit;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteStub DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteStub:112
public class BStub_LemonService extends BStub implements LemonServiceAuth, java.io.Serializable {
	
	// checkpoint byps.gen.j.GenRemoteStub:93
	public static final long serialVersionUID = 605543968L;
	protected final BForward_LemonService forwardTo;	
	
	@SuppressWarnings("unused") private BStub_LemonService() {
		this.forwardTo = new BForward_LemonService();
	}
	
	public BStub_LemonService(final BTransport transport) {
		super(transport);
		this.forwardTo = new BForward_LemonService(transport);
		
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public java.lang.String squeeze() throws RemoteException{
	  return forwardTo.squeeze();
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void squeeze(final BAsyncResult<String> asyncResult) {
	  forwardTo.squeeze(asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public java.lang.String grow() throws RemoteException{
	  return forwardTo.grow();
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void grow(final BAsyncResult<String> asyncResult) {
	  forwardTo.grow(asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public java.lang.String pick(byps.test.api.auth.SessionInfo sess, java.lang.String fromTree) throws RemoteException{
	  return forwardTo.pick(sess, fromTree);
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void pick(byps.test.api.auth.SessionInfo sess, java.lang.String fromTree, final BAsyncResult<String> asyncResult) {
	  forwardTo.pick(sess, fromTree, asyncResult);
	}
	
	
}
