package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_TaskService_removeTask extends BMethodRequest implements Serializable {

	public Token token;
	public long taskId;
	
	public final static long serialVersionUID = 1265487020L;
	
	public int getRemoteId() { return 216769899; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final TaskServiceAsync __byps__remoteT = (TaskServiceAsync)__byps__remote;			
			BAsyncResultSendMethod<Object> __byps__outerResult = new BAsyncResultSendMethod<Object>(__byps__asyncResult, new BResult_19());			
			__byps__remoteT.removeTask(token, taskId, __byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
		}
	}	
	
	public String toString() {
		StringBuilder s = new StringBuilder();
		s.append("[TaskService.removeTask(");
		s.append(token);
		s.append(",").append(taskId);
		s.append(")]");
		return s.toString();
	}
	
}
