package task.app;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_323961470 extends BMethodResult<Token> implements Serializable {

	
	public final static long serialVersionUID = 771996649L;
	
}
