package task.app;

/*
 * Serializer for task.app.BRequest_TaskService_addTask
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1498136965 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1498136965();
	
	public JSerializer_1498136965() {
		super(1498136965);
	}
	
	public JSerializer_1498136965(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_TaskService_addTask obj = (BRequest_TaskService_addTask)obj1;		
		bout.writeObj("task",obj.task, false, null);
		bout.writeObj("token",obj.token, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_TaskService_addTask obj = (BRequest_TaskService_addTask)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_TaskService_addTask()));
		
		final BJsonObject js = bin.currentObject;
		obj.task = (task.app.TaskInfo)bin.readObj("task", false, null);
		obj.token = (task.app.Token)bin.readObj("token", false, null);
		
		return obj;
	}
	
}
