package byps.test.api.cons;

/*
 * Serializer for byps.test.api.cons.ConfigResultOption
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:304
@SuppressWarnings("all")
public class JSerializer_1292137034 extends byps.JSerializer_22 {
	
	public final static BSerializer instance = new JSerializer_1292137034();
	
	public JSerializer_1292137034() {
		super(1292137034);
	}
	
	public JSerializer_1292137034(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final ConfigResultOption obj = (ConfigResultOption)obj1;		
		super.internalWrite(obj1, bout, bbuf);		
		bbuf.putInt("groupingType", obj.groupingType!=null ? obj.groupingType.ordinal() : 0);
		bbuf.putString("string1", obj.string1);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final ConfigResultOption obj = (ConfigResultOption)(obj1 != null ? obj1 : bin.onObjectCreated(new ConfigResultOption()));
		
		// Read base class members
		super.internalRead(obj, bin);
		
		final BJsonObject js = bin.currentObject;
		obj.groupingType = BEnumHelper.fromOrdinal(byps.test.api.cons.GroupingType.values(), js.getInt("groupingType"));
		obj.string1 = js.getString("string1");
		
		return obj;
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		super.prepareForLazyLoading(obj1, bin, version);
		final ConfigResultOption obj = (ConfigResultOption)(obj1);		
		
	}
	
}
