package byps.test.api;

/*
 * Serializer for byps.test.api.prim.PrimitiveTypes[]
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerArrayJson DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_2053507648 extends JSerializer_Array {
	
	public final static BSerializer instance = new JSerializer_2053507648();
	
	public JSerializer_2053507648() {
		super(2053507648);
	}
	
	@Override
	public Object internalRead(final BInputJson bin) throws BException {
		final BJsonObject js0 = bin.currentObject;
		
		int n0 = 0;
		n0 = js0 != null ? js0.size() : 0;
		
		final byps.test.api.prim.PrimitiveTypes[] arr =  new byps.test.api.prim.PrimitiveTypes[n0];
		bin.onObjectCreated(arr);
		
		// read
		final byps.test.api.prim.PrimitiveTypes[] a0 = arr;
		for (int i0 = 0; i0 < n0; i0++) {
			a0[i0] = (byps.test.api.prim.PrimitiveTypes)bin.readObj(i0, false, null);
		}
		return arr;
		
	}
	
	@Override
	public void internalWrite(Object obj1, final BOutputJson bout, BBufferJson bbuf) throws BException {
		final byps.test.api.prim.PrimitiveTypes[] arr = (byps.test.api.prim.PrimitiveTypes[])obj1;
		
		// lengths
		final int n0 = arr.length;
		
		// write
		final byps.test.api.prim.PrimitiveTypes[] a0 = arr;
		bbuf.beginArray();
		for (int i0 = 0; i0 < n0; i0++) {
			// checkpoint byps.gen.j.PrintContext:329
			bout.writeObj(null, a0[i0], false, null);
		}
		bbuf.endArray();
	}
	
}
