package byps.test.api;

/*
 * Serializer for byps.test.api.BResult_945713488
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1852992857 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1852992857();
	
	public JSerializer_1852992857() {
		super(1852992857);
	}
	
	public JSerializer_1852992857(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_945713488 obj = (BResult_945713488)obj1;		
		bout.writeObj("result",obj.result, false, byps.test.api.JSerializer_945713488.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_945713488 obj = (BResult_945713488)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_945713488()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (boolean[][][][])bin.readObj("result", false, byps.test.api.JSerializer_945713488.instance);
		
		return obj;
	}
	
}
