package byps.test.api;

/*
 * Serializer for java.util.Map<java.lang.String,byps.test.api.inherit.Class1>
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerMapJson DO NOT MODIFY.
 */

import byps.*;
import java.util.*;

@SuppressWarnings("all")
public class JSerializer_2058676657 extends JSerializer_13 {
	
	public final static BSerializer instance = new JSerializer_2058676657();
	
	public JSerializer_2058676657() {
		super(2058676657);	}
	
	
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputJson bin = (BInputJson)bin1;
		final BJsonObject js = bin.currentObject;
		final Set<String> keys = js.keys();
		final HashMap<java.lang.String,byps.test.api.inherit.Class1> map = new HashMap<java.lang.String,byps.test.api.inherit.Class1>(keys.size());
		bin.onObjectCreated(map);
		for (String keyName : keys) {
			java.lang.String key = keyName;
			final byps.test.api.inherit.Class1 value = (byps.test.api.inherit.Class1)bin.readObj(keyName, false, null);
			map.put(key, value);
		}
		return map;
	}
	
	@Override
	protected void internalWriteKeyValue(final BOutputJson bout, final BBufferJson bbuf, final Object key, final Object value) throws BException {
		final String keyName = key != null ? (String)key : "";
		bout.writeObj(keyName, value, false, null);
	}
	
}
