package byps.test.api;

/*
 * Serializer for byps.test.api.BResult_2123584667
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_253151806 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_253151806();
	
	public JSerializer_253151806() {
		super(253151806);
	}
	
	public JSerializer_253151806(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_2123584667 obj = (BResult_2123584667)obj1;		
		bout.writeObj("result",obj.result, false, byps.test.api.JSerializer_2123584667.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_2123584667 obj = (BResult_2123584667)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_2123584667()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (java.util.List<java.lang.String>)bin.readObj("result", false, byps.test.api.JSerializer_2123584667.instance);
		
		return obj;
	}
	
}
