package byps.test.api;

/*
 * Serializer for byps.test.api.cons.AllTypesZ[]
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerArrayJson DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings({"all","deprecation","unchecked","rawtypes","cast","static","try","serial","this-escape"})
public class JSerializer_85091 extends JSerializer_Array {
	
	public final static BSerializer instance = new JSerializer_85091();
	
	public JSerializer_85091() {
		super(85091);
	}
	
	@Override
	public Object internalRead(final BInputJson bin) throws BException {
		final BJsonObject js0 = bin.currentObject;
		
		int n0 = 0;
		n0 = js0 != null ? js0.size() : 0;
		
		final byps.test.api.cons.AllTypesZ[] arr =  new byps.test.api.cons.AllTypesZ[n0];
		bin.onObjectCreated(arr);
		
		// read
		final byps.test.api.cons.AllTypesZ[] a0 = arr;
		for (int i0 = 0; i0 < n0; i0++) {
			a0[i0] = (byps.test.api.cons.AllTypesZ)bin.readObj(i0, false, null);
		}
		return arr;
		
	}
	
	@Override
	public void internalWrite(Object obj1, final BOutputJson bout, BBufferJson bbuf) throws BException {
		final byps.test.api.cons.AllTypesZ[] arr = (byps.test.api.cons.AllTypesZ[])obj1;
		
		// lengths
		final int n0 = arr.length;
		
		// write
		final byps.test.api.cons.AllTypesZ[] a0 = arr;
		bbuf.beginArray();
		for (int i0 = 0; i0 < n0; i0++) {
			// checkpoint byps.gen.j.PrintContext:342
			bout.writeObj(null, a0[i0], false, null);
		}
		bbuf.endArray();
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		byps.test.api.cons.AllTypesZ[] arr = (byps.test.api.cons.AllTypesZ[])obj1;
		final int n0 = arr.length;
		
		final byps.test.api.cons.AllTypesZ[] a0 = arr;
		for (int i0 = 0; i0 < n0; i0++) {
			bin.prepareForLazyLoading(a0[i0], null);
		}
	}
	
}
