package byps.test.api;

/*
 * Serializer for byps.test.api.BResult_2064980445
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:304
@SuppressWarnings("all")
public class JSerializer_937508540 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_937508540();
	
	public JSerializer_937508540() {
		super(937508540);
	}
	
	public JSerializer_937508540(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_2064980445 obj = (BResult_2064980445)obj1;		
		bout.writeObj("result",obj.result, false, byps.test.api.JSerializer_2064980445.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_2064980445 obj = (BResult_2064980445)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_2064980445()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (java.util.List<byps.test.api.inl.Point2D>)bin.readObj("result", false, byps.test.api.JSerializer_2064980445.instance);
		
		return obj;
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		final BResult_2064980445 obj = (BResult_2064980445)(obj1);		
		bin.prepareForLazyLoading(obj.result, byps.test.api.BSerializer_2064980445.instance);
		
	}
	
}
