package byps.test.api;

/*
 * Serializer for java.util.Set<byps.test.api.prim.PrimitiveTypes>
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerListJson DO NOT MODIFY.
 */

import byps.*;
import java.util.*;

@SuppressWarnings("all")
public class JSerializer_673917574 extends BSerializer {
	
	public final static BSerializer instance = new JSerializer_673917574();
	
	public JSerializer_673917574() {
		super(673917574);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputJson bin = (BInputJson)bin1;
		final BBufferJson bbuf = bin.bbuf;
		final int n = bin.currentObject.size();
		final HashSet<byps.test.api.prim.PrimitiveTypes> arr = new HashSet<byps.test.api.prim.PrimitiveTypes>();
		bin.onObjectCreated(arr);
		for (int i0 = 0; i0 < n; i0++) {
			byps.test.api.prim.PrimitiveTypes obj = (byps.test.api.prim.PrimitiveTypes)bin.readObj(i0, false, null);
			arr.add(obj);
		}
		return arr;
	}
	
	@Override
	public void write(Object obj1, BOutput bout1, final long version)  throws BException {
		BOutputJson bout = (BOutputJson)bout1;
		BBufferJson bbuf = bout.bbuf;
		java.util.Set<byps.test.api.prim.PrimitiveTypes> arr = (java.util.Set<byps.test.api.prim.PrimitiveTypes>)obj1;
		int n = arr.size();
		bbuf.beginArray();
		for (byps.test.api.prim.PrimitiveTypes obj : arr) {
			// checkpoint byps.gen.j.PrintContext:327
			bout.writeObj(null, obj, false, null);
		}
		bbuf.endArray();
	}
	
}
