package byps.test.api.inherit;

/*
 * Serializer for byps.test.api.inherit.BStub_BioLemonService
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class BSerializer_501819909 extends BSerializer_16 {
	
	public final static BSerializer instance = new BSerializer_501819909();
	
	public BSerializer_501819909() {
		super(501819909);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_BioLemonService(transport);
	}
	
}
