package byps.test.api.srvr;

/*
 * Serializer for byps.test.api.srvr.ChatStructure
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=false
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:304
@SuppressWarnings("all")
public class BSerializer_7007 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_7007();
	
	public BSerializer_7007() {
		super(7007);
	}
	
	public BSerializer_7007(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final ChatStructure obj = (ChatStructure)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putString(obj.msg);
		bbuf.putDouble(obj.receivedAt);
		bbuf.putDouble(obj.sentAt);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final ChatStructure obj = (ChatStructure)(obj1 != null ? obj1 : bin.onObjectCreated(new ChatStructure()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.msg = bbuf.getString();
		obj.receivedAt = bbuf.getDouble();
		obj.sentAt = bbuf.getDouble();
		
		return obj;
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		final ChatStructure obj = (ChatStructure)(obj1);		
		
	}
	
}
