package com.wilutions.byps.test.api.srvr;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import com.wilutions.byps.*;

// checkpoint com.wilutions.byps.gen.j.GenRemoteClassAsync:64
public interface ClientIFAsync extends ClientIF, BRemote {

	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public int incrementInt(int a) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void incrementInt(int a, final BAsyncResult<Integer> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.io.InputStream> getStreams(int ctrl) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getStreams(int ctrl, final BAsyncResult<java.util.List<java.io.InputStream>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void putStreams(java.util.List<java.io.InputStream> strm, int ctrl) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void putStreams(java.util.List<java.io.InputStream> strm, int ctrl, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public ChatStructure sendChat(ChatStructure cs) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void sendChat(ChatStructure cs, final BAsyncResult<ChatStructure> asyncResult) ;
	
	
}
