package byps.test.api;

/*
 * Serializer for java.util.Map<java.lang.Integer,int[]>
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerMap DO NOT MODIFY.
 */

import byps.*;
import java.util.*;

@SuppressWarnings("all")
public class BSerializer_1633750383 extends BSerializer_13 {
	
	public final static BSerializer instance = new BSerializer_1633750383();
	
	public BSerializer_1633750383() {
		super(1633750383);	}
	
	
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BBufferBin bbuf = bin.bbuf;
		final HashMap<java.lang.Integer,int[]> map = new HashMap<java.lang.Integer,int[]>();
		bin.onObjectCreated(map);
		int n = bbuf.getLength();
		for (int i0 = 0; i0 < n; i0++) {
			java.lang.Integer key = bbuf.getInt();
			int[] value = (int[])bin.readObj(false, byps.test.api.BSerializer_100361105.instance);
			map.put(key, value);
		}
		return map;
	}
	
	public void write(Object obj1, BOutput bout1, final long version)  throws BException {
		BOutputBin bout = (BOutputBin)bout1;
		BBufferBin bbuf = bout.bbuf;
		Map<java.lang.Integer,int[]> map = (Map<java.lang.Integer,int[]>)obj1;
		int n = map.size();
		bbuf.putLength(n);
		for (Map.Entry<java.lang.Integer,int[]> obj : map.entrySet()) {
			bbuf.putInt(obj.getKey() != null ? (Integer)obj.getKey() : 0);
			bout.writeObj(obj.getValue(), false, byps.test.api.BSerializer_100361105.instance);
		}
	}
	
}
