package byps.test.api;

/*
 * Serializer for byps.test.api.BResult_949340697
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:304
@SuppressWarnings("all")
public class BSerializer_996206823 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_996206823();
	
	public BSerializer_996206823() {
		super(996206823);
	}
	
	public BSerializer_996206823(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BResult_949340697 obj = (BResult_949340697)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.result, false, byps.test.api.BSerializer_949340697.instance);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BResult_949340697 obj = (BResult_949340697)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_949340697()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.result = (byps.test.api.inl.Point2D[][][][])bin.readObj(false, byps.test.api.BSerializer_949340697.instance);
		
		return obj;
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		final BResult_949340697 obj = (BResult_949340697)(obj1);		
		bin.prepareForLazyLoading(obj.result, byps.test.api.BSerializer_949340697.instance);
		
	}
	
}
