package byps.test.api;

/*
 * Serializer for byps.test.api.BResult_588723219
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1537615291 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1537615291();
	
	public BSerializer_1537615291() {
		super(1537615291);
	}
	
	public BSerializer_1537615291(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BResult_588723219 obj = (BResult_588723219)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.result, true, byps.test.api.BSerializer_588723219.instance);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BResult_588723219 obj = (BResult_588723219)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_588723219()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.result = (java.lang.String[][][][])bin.readObj(true, byps.test.api.BSerializer_588723219.instance);
		
		return obj;
	}
	
}
