package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1473575576 extends BMethodResult<com.wilutions.byps.test.api.srvr.ClientIF> implements Serializable {

	
	public final static long serialVersionUID = 1170836883L;
	
}
