package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1174971318 extends BMethodResult<java.util.List<byte[]>> implements Serializable {

	
	public final static long serialVersionUID = 994835305L;
	
}
