package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_2058423690 extends BMethodResult<boolean[]> implements Serializable {

	
	public final static long serialVersionUID = 532799052L;
	
}
