package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1973996106 extends BMethodResult<java.util.Map<java.lang.Short,java.lang.Long>> implements Serializable {

	
	public final static long serialVersionUID = 839888536L;
	
}
