package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1888799711 extends BMethodResult<java.util.Set<java.lang.String>> implements Serializable {

	
	private final static long serialVersionUID = 180574010L;
	
}
