package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1059148284 extends BMethodResult<java.util.List<java.lang.Byte>> implements Serializable {

	
	private final static long serialVersionUID = 1532920911L;
	
}
