package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1859644668 extends BMethodResult<short[][][][]> implements Serializable {

	
	private final static long serialVersionUID = 101217472L;
	
}
