package com.wilutions.byps.test.api;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import com.wilutions.byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BResult_1457164460 extends BMethodResult<java.util.Set<java.lang.Long>> implements Serializable {

	
	private final static long serialVersionUID = 1119760023L;
	
}
