package task.app;

/*
 * Serializer for task.app.BResult_1182472339
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_2101800006 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_2101800006();
	
	public JSerializer_2101800006() {
		super(2101800006);
	}
	
	public JSerializer_2101800006(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BResult_1182472339 obj = (BResult_1182472339)obj1;		
		bout.writeObj("result",obj.result, false, task.app.JSerializer_1182472339.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BResult_1182472339 obj = (BResult_1182472339)(obj1 != null ? obj1 : bin.onObjectCreated(new BResult_1182472339()));
		
		final BJsonObject js = bin.currentObject;
		obj.result = (java.util.List<task.app.TaskInfo>)bin.readObj("result", false, task.app.JSerializer_1182472339.instance);
		
		return obj;
	}
	
}
