package byps.test.api.ver;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface EvolveIFAsync extends BRemote, 
	EvolveIF {
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setEvolve(Evolve obj) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setEvolve(Evolve obj, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public Evolve getEvolve() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getEvolve(final BAsyncResult<Evolve> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setClient(EvolveIF partner) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setClient(EvolveIF partner, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public EvolveIF getClient() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getClient(final BAsyncResult<EvolveIF> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void sendEvolveToClient() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void sendEvolveToClient(final BAsyncResult<Object> asyncResult) ;
	
	
}
