package com.wilutions.byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import com.wilutions.byps.*;

// checkpoint com.wilutions.byps.gen.j.GenRemoteClassAsync:64
public interface RemoteArrayTypes4dimAsync extends RemoteArrayTypes4dim, BRemote {

	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setBool(boolean[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setBool(boolean[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setByte(byte[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setByte(byte[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setChar(char[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setChar(char[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setShort(short[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setShort(short[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setInt(int[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setInt(int[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setLong(long[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setLong(long[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setFloat(float[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setFloat(float[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setDouble(double[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setDouble(double[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setString(java.lang.String[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setString(java.lang.String[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setPrimitiveTypes(com.wilutions.byps.test.api.prim.PrimitiveTypes[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setPrimitiveTypes(com.wilutions.byps.test.api.prim.PrimitiveTypes[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setObject(java.lang.Object[][][][] v) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setObject(java.lang.Object[][][][] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public boolean[][][][] getBool() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getBool(final BAsyncResult<boolean[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public byte[][][][] getByte() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getByte(final BAsyncResult<byte[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public char[][][][] getChar() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getChar(final BAsyncResult<char[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public short[][][][] getShort() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getShort(final BAsyncResult<short[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public int[][][][] getInt() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getInt(final BAsyncResult<int[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public long[][][][] getLong() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getLong(final BAsyncResult<long[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public float[][][][] getFloat() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getFloat(final BAsyncResult<float[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public double[][][][] getDouble() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getDouble(final BAsyncResult<double[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.lang.String[][][][] getString() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getString(final BAsyncResult<java.lang.String[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public com.wilutions.byps.test.api.prim.PrimitiveTypes[][][][] getPrimitiveTypes() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getPrimitiveTypes(final BAsyncResult<com.wilutions.byps.test.api.prim.PrimitiveTypes[][][][]> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.lang.Object[][][][] getObject() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getObject(final BAsyncResult<java.lang.Object[][][][]> asyncResult) ;
	
	
}
