package com.wilutions.byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class com.wilutions.byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import com.wilutions.byps.*;

// checkpoint com.wilutions.byps.gen.j.GenRemoteClassAsync:64
public interface RemoteListTypesAsync extends RemoteListTypes, BRemote {

	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Boolean> getBoolean1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getBoolean1(final BAsyncResult<java.util.List<java.lang.Boolean>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setBoolean1(java.util.List<java.lang.Boolean> boolean1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setBoolean1(java.util.List<java.lang.Boolean> boolean1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Byte> getByte1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getByte1(final BAsyncResult<java.util.List<java.lang.Byte>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setByte1(java.util.List<java.lang.Byte> byte1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setByte1(java.util.List<java.lang.Byte> byte1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Character> getChar1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getChar1(final BAsyncResult<java.util.List<java.lang.Character>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setChar1(java.util.List<java.lang.Character> char1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setChar1(java.util.List<java.lang.Character> char1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Short> getShort1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getShort1(final BAsyncResult<java.util.List<java.lang.Short>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setShort1(java.util.List<java.lang.Short> short1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setShort1(java.util.List<java.lang.Short> short1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Integer> getInt1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getInt1(final BAsyncResult<java.util.List<java.lang.Integer>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setInt1(java.util.List<java.lang.Integer> int1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setInt1(java.util.List<java.lang.Integer> int1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Long> getLong1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getLong1(final BAsyncResult<java.util.List<java.lang.Long>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setLong1(java.util.List<java.lang.Long> long1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setLong1(java.util.List<java.lang.Long> long1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Float> getFloat1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getFloat1(final BAsyncResult<java.util.List<java.lang.Float>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setFloat1(java.util.List<java.lang.Float> float1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setFloat1(java.util.List<java.lang.Float> float1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Double> getDouble1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getDouble1(final BAsyncResult<java.util.List<java.lang.Double>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setDouble1(java.util.List<java.lang.Double> double1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setDouble1(java.util.List<java.lang.Double> double1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.String> getString1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getString1(final BAsyncResult<java.util.List<java.lang.String>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setString1(java.util.List<java.lang.String> string1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setString1(java.util.List<java.lang.String> string1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<com.wilutions.byps.test.api.prim.PrimitiveTypes> getPrimitiveTypes1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getPrimitiveTypes1(final BAsyncResult<java.util.List<com.wilutions.byps.test.api.prim.PrimitiveTypes>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setPrimitiveTypes1(java.util.List<com.wilutions.byps.test.api.prim.PrimitiveTypes> primitiveTypes1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setPrimitiveTypes1(java.util.List<com.wilutions.byps.test.api.prim.PrimitiveTypes> primitiveTypes1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<byte[]> getByte2() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getByte2(final BAsyncResult<java.util.List<byte[]>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setByte2(java.util.List<byte[]> byte2) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setByte2(java.util.List<byte[]> byte2, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<int[]> getInt2() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getInt2(final BAsyncResult<java.util.List<int[]>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setInt2(java.util.List<int[]> int2) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setInt2(java.util.List<int[]> int2, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.lang.Object> getObj1() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getObj1(final BAsyncResult<java.util.List<java.lang.Object>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setObj1(java.util.List<java.lang.Object> obj1) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setObj1(java.util.List<java.lang.Object> obj1, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.util.List<java.lang.Integer>> getInt3() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getInt3(final BAsyncResult<java.util.List<java.util.List<java.lang.Integer>>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setInt3(java.util.List<java.util.List<java.lang.Integer>> int3) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setInt3(java.util.List<java.util.List<java.lang.Integer>> int3, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public java.util.List<java.util.Map<java.lang.Integer,java.util.List<java.util.TreeSet<java.lang.Integer>>>> getInt4() throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void getInt4(final BAsyncResult<java.util.List<java.util.Map<java.lang.Integer,java.util.List<java.util.TreeSet<java.lang.Integer>>>>> asyncResult) ;
	
	/**
	*/
	// checkpoint com.wilutions.byps.gen.j.PrintContext:356
	public void setInt4(java.util.List<java.util.Map<java.lang.Integer,java.util.List<java.util.TreeSet<java.lang.Integer>>>> int4) throws RemoteException;
	// checkpoint com.wilutions.byps.gen.j.PrintContext:400
	public void setInt4(java.util.List<java.util.Map<java.lang.Integer,java.util.List<java.util.TreeSet<java.lang.Integer>>>> int4, final BAsyncResult<Object> asyncResult) ;
	
	
}
