package byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteProxy DO NOT MODIFY.
 */

import byps.*;

/**
 * This class provides a proxy implementation of the interface RemoteEnums.
 */
@SuppressWarnings("all")
public class BProxy_RemoteEnums extends BSkeleton_RemoteEnums implements RemoteEnumsAsync {
	
	public static final long serialVersionUID = 485761455L;
	
	protected final byps.test.api.remote.RemoteEnumsAsync forwardTo;
	
	public BProxy_RemoteEnums(RemoteEnumsAsync forwardTo) {
		this.forwardTo = forwardTo;
	}
	
	public BProxy_RemoteEnums(BTransport transport) {
		this(new BForward_RemoteEnums(transport));
	}
	
	// checkpoint byps.gen.j.PrintContext:385
	public byps.test.api.enu.EnumPlanets getPlanet() throws RemoteException{
	  return forwardTo.getPlanet();
	}
	// checkpoint byps.gen.j.PrintContext:429
	public void getPlanet(final BAsyncResult<byps.test.api.enu.EnumPlanets> asyncResult) {
	  forwardTo.getPlanet(asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:385
	public void setPlanet(byps.test.api.enu.EnumPlanets planet) throws RemoteException{
	  forwardTo.setPlanet(planet);
	}
	// checkpoint byps.gen.j.PrintContext:429
	public void setPlanet(byps.test.api.enu.EnumPlanets planet, final BAsyncResult<Object> asyncResult) {
	  forwardTo.setPlanet(planet, asyncResult);
	}
	
	
}
