package byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenApiClass DO NOT MODIFY.
 */

import byps.*;
import java.io.Serializable;

/**
*/
@SuppressWarnings("all")
public final class BRequest_RemoteMapTypes_getDate1 extends BMethodRequest implements Serializable {

	
	public final static long serialVersionUID = 123590589L;
	
	public int getRemoteId() { return 1277224527; }
	
	public void execute(BRemote __byps__remote, BAsyncResult<Object> __byps__asyncResult) throws Throwable {
		try {
			final RemoteMapTypesAsync __byps__remoteT = (RemoteMapTypesAsync)__byps__remote;			
			BAsyncResultSendMethod<java.util.Map<java.lang.String,java.util.Date>> __byps__outerResult = new BAsyncResultSendMethod<java.util.Map<java.lang.String,java.util.Date>>(__byps__asyncResult, new byps.test.api.BResult_1366799209());			
			__byps__remoteT.getDate1(__byps__outerResult);
		} catch (Throwable e) {
			__byps__asyncResult.setAsyncResult(null, e);
			throw e;
		}
	}	
	
}
