package byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteStub DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteStub:112
public class BStub_RemoteEnums extends BStub implements RemoteEnumsAsync, java.io.Serializable {
	
	// checkpoint byps.gen.j.GenRemoteStub:93
	public static final long serialVersionUID = 485761455L;
	protected final BForward_RemoteEnums forwardTo;	
	
	@SuppressWarnings("unused") private BStub_RemoteEnums() {
		this.forwardTo = new BForward_RemoteEnums();
	}
	
	public BStub_RemoteEnums(final BTransport transport) {
		super(transport);
		this.forwardTo = new BForward_RemoteEnums(transport);
		
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public byps.test.api.enu.EnumPlanets getPlanet() throws RemoteException{
	  return forwardTo.getPlanet();
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void getPlanet(final BAsyncResult<byps.test.api.enu.EnumPlanets> asyncResult) {
	  forwardTo.getPlanet(asyncResult);
	}
	
	// checkpoint byps.gen.j.PrintContext:398
	public void setPlanet(byps.test.api.enu.EnumPlanets planet) throws RemoteException{
	  forwardTo.setPlanet(planet);
	}
	// checkpoint byps.gen.j.PrintContext:442
	public void setPlanet(byps.test.api.enu.EnumPlanets planet, final BAsyncResult<Object> asyncResult) {
	  forwardTo.setPlanet(planet, asyncResult);
	}
	
	
}
