package byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface RemoteArrayTypes1dimAsync extends BRemote, 
	RemoteArrayTypes1dim {
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setBool(boolean[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setBool(boolean[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setByte(byte[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setByte(byte[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setChar(char[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setChar(char[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setShort(short[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setShort(short[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setInt(int[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setInt(int[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setLong(long[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setLong(long[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setFloat(float[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setFloat(float[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setDouble(double[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setDouble(double[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setString(java.lang.String[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setString(java.lang.String[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setPrimitiveTypes(byps.test.api.prim.PrimitiveTypes[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setPrimitiveTypes(byps.test.api.prim.PrimitiveTypes[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setObject(java.lang.Object[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setObject(java.lang.Object[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public void setDate(java.util.Date[] v) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void setDate(java.util.Date[] v, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public boolean[] getBool() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getBool(final BAsyncResult<boolean[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public byte[] getByte() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getByte(final BAsyncResult<byte[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public char[] getChar() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getChar(final BAsyncResult<char[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public short[] getShort() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getShort(final BAsyncResult<short[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public int[] getInt() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getInt(final BAsyncResult<int[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public long[] getLong() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getLong(final BAsyncResult<long[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public float[] getFloat() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getFloat(final BAsyncResult<float[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public double[] getDouble() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getDouble(final BAsyncResult<double[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public java.lang.String[] getString() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getString(final BAsyncResult<java.lang.String[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public byps.test.api.prim.PrimitiveTypes[] getPrimitiveTypes() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getPrimitiveTypes(final BAsyncResult<byps.test.api.prim.PrimitiveTypes[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public java.lang.Object[] getObject() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getObject(final BAsyncResult<java.lang.Object[]> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:365
	public java.util.Date[] getDate() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:409
	public void getDate(final BAsyncResult<java.util.Date[]> asyncResult) ;
	
	
}
