package byps.test.api.remote;

/*
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenRemoteClassAsync DO NOT MODIFY.
 */

import byps.*;

// checkpoint byps.gen.j.GenRemoteClassAsync:68
public interface RemoteStreamsAsync extends BRemote, 
	RemoteStreams {
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public java.io.InputStream getImage() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void getImage(final BAsyncResult<java.io.InputStream> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public void setImage(java.io.InputStream istrm) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void setImage(java.io.InputStream istrm, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public java.util.TreeMap<java.lang.Integer,java.io.InputStream> getImages() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void getImages(final BAsyncResult<java.util.TreeMap<java.lang.Integer,java.io.InputStream>> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public void setImages(java.util.Map<java.lang.Integer,java.io.InputStream> istrms, int doNotReadStreamAtKey) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void setImages(java.util.Map<java.lang.Integer,java.io.InputStream> istrms, int doNotReadStreamAtKey, final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public void throwLastException() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void throwLastException(final BAsyncResult<Object> asyncResult) ;
	
	/**
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public java.io.InputStream getTextStream() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void getTextStream(final BAsyncResult<java.io.InputStream> asyncResult) ;
	
	/**
	 * Return a large video stream to be able to test that byte ranges are correctly handled.
	 * This functionality is currently only tested in the JSON API by TestVideoCheckSupportByteRange.html.
	 * @return InputStream
	 * @throws RemoteException
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public java.io.InputStream getVideoCheckSupportByteRange() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void getVideoCheckSupportByteRange(final BAsyncResult<java.io.InputStream> asyncResult) ;
	
	/**
	 * Return stream without properties.
	 * The properties must be made explicitly available on the client-side by calling
	 * BContentStream.ensureProperties()
	 * @return InputStream
	 * @throws RemoteException
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public java.io.InputStream getStreamDeferedProperies() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void getStreamDeferedProperies(final BAsyncResult<java.io.InputStream> asyncResult) ;
	
	/**
	 * Stores a stream reference but does not create an internal copy (does not materialize)
	 * @param stream
	 * @throws RemoteException
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public void setStreamDoNotMaterialize(java.io.InputStream stream) throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void setStreamDoNotMaterialize(java.io.InputStream stream, final BAsyncResult<Object> asyncResult) ;
	
	/**
	 * Return stream, do not call BContentStream.cloneStream().
	 * @throws RemoteException
	*/
	// checkpoint byps.gen.j.PrintContext:383
	public java.io.InputStream getStreamDoNotClone() throws RemoteException;
	// checkpoint byps.gen.j.PrintContext:427
	public void getStreamDoNotClone(final BAsyncResult<java.io.InputStream> asyncResult) ;
	
	
}
