package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemotePrimitiveTypes_getDeferredValueFromServer
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:304
@SuppressWarnings("all")
public class JSerializer_547282058 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_547282058();
	
	public JSerializer_547282058() {
		super(547282058);
	}
	
	public JSerializer_547282058(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_RemotePrimitiveTypes_getDeferredValueFromServer obj = (BRequest_RemotePrimitiveTypes_getDeferredValueFromServer)obj1;		
		bbuf.putInt("param1", obj.param1);
		bbuf.putString("param2", obj.param2);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_RemotePrimitiveTypes_getDeferredValueFromServer obj = (BRequest_RemotePrimitiveTypes_getDeferredValueFromServer)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemotePrimitiveTypes_getDeferredValueFromServer()));
		
		final BJsonObject js = bin.currentObject;
		obj.param1 = js.getInt("param1");
		obj.param2 = js.getString("param2");
		
		return obj;
	}
	
	@Override
	public void prepareForLazyLoading(final Object obj1, final BInput bin, final long version) throws BException {
		final BRequest_RemotePrimitiveTypes_getDeferredValueFromServer obj = (BRequest_RemotePrimitiveTypes_getDeferredValueFromServer)(obj1);		
		
	}
	
}
