package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BStub_RemoteInlineInstance
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_355071648 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_355071648();
	
	public JSerializer_355071648() {
		super(355071648);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_RemoteInlineInstance(transport);
	}
	
}
