package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BStub_RemoteStreams
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1043578866 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1043578866();
	
	public JSerializer_1043578866() {
		super(1043578866);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_RemoteStreams(transport);
	}
	
}
