package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BStub_RemoteWithAuthentication
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1532028880 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1532028880();
	
	public JSerializer_1532028880() {
		super(1532028880);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_RemoteWithAuthentication(transport);
	}
	
}
