package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BStub_RemoteSetTypes
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1781251319 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1781251319();
	
	public JSerializer_1781251319() {
		super(1781251319);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_RemoteSetTypes(transport);
	}
	
}
