package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemoteArrayTypes23_sendArraysObject
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=3

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1306614381 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1306614381();
	
	public JSerializer_1306614381() {
		super(1306614381);
	}
	
	public JSerializer_1306614381(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_RemoteArrayTypes23_sendArraysObject obj = (BRequest_RemoteArrayTypes23_sendArraysObject)obj1;		
		bout.writeObj("arr2",obj.arr2, false, byps.test.api.JSerializer_340213335.instance);
		bout.writeObj("arr3",obj.arr3, false, byps.test.api.JSerializer_527503353.instance);
		bout.writeObj("arr4",obj.arr4, false, byps.test.api.JSerializer_124584219.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_RemoteArrayTypes23_sendArraysObject obj = (BRequest_RemoteArrayTypes23_sendArraysObject)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemoteArrayTypes23_sendArraysObject()));
		
		final BJsonObject js = bin.currentObject;
		obj.arr2 = (java.lang.Object[][])bin.readObj("arr2", false, byps.test.api.JSerializer_340213335.instance);
		obj.arr3 = (java.lang.Object[][][])bin.readObj("arr3", false, byps.test.api.JSerializer_527503353.instance);
		obj.arr4 = (java.lang.Object[][][][])bin.readObj("arr4", false, byps.test.api.JSerializer_124584219.instance);
		
		return obj;
	}
	
}
