package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemoteArrayTypes4dim_setBool
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_185807085 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_185807085();
	
	public JSerializer_185807085() {
		super(185807085);
	}
	
	public JSerializer_185807085(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_RemoteArrayTypes4dim_setBool obj = (BRequest_RemoteArrayTypes4dim_setBool)obj1;		
		bout.writeObj("v",obj.v, false, byps.test.api.JSerializer_945713488.instance);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_RemoteArrayTypes4dim_setBool obj = (BRequest_RemoteArrayTypes4dim_setBool)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemoteArrayTypes4dim_setBool()));
		
		final BJsonObject js = bin.currentObject;
		obj.v = (boolean[][][][])bin.readObj("v", false, byps.test.api.JSerializer_945713488.instance);
		
		return obj;
	}
	
}
