package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BStub_RemoteListTypes
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class JSerializer_1240892695 extends JSerializer_16 {
	
	public final static BSerializer instance = new JSerializer_1240892695();
	
	public JSerializer_1240892695() {
		super(1240892695);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_RemoteListTypes(transport);
	}
	
}
