package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemoteWithAuthentication_doit
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStructJson DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class JSerializer_1251509013 extends JSerializer_Object {
	
	public final static BSerializer instance = new JSerializer_1251509013();
	
	public JSerializer_1251509013() {
		super(1251509013);
	}
	
	public JSerializer_1251509013(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void internalWrite(final Object obj1, final BOutputJson bout, final BBufferJson bbuf) throws BException {
		final BRequest_RemoteWithAuthentication_doit obj = (BRequest_RemoteWithAuthentication_doit)obj1;		
		bbuf.putInt("value", obj.value);
		bout.writeObj("sess",obj.sess, false, null);
	}
	
	@Override
	public Object internalRead(final Object obj1, final BInputJson bin) throws BException {
		final BRequest_RemoteWithAuthentication_doit obj = (BRequest_RemoteWithAuthentication_doit)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemoteWithAuthentication_doit()));
		
		final BJsonObject js = bin.currentObject;
		obj.value = js.getInt("value");
		obj.sess = (byps.test.api.auth.SessionInfo)bin.readObj("sess", false, null);
		
		return obj;
	}
	
}
