package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemoteConstants_compare_HebrewC
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=2

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1711871378 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1711871378();
	
	public BSerializer_1711871378() {
		super(1711871378);
	}
	
	public BSerializer_1711871378(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_RemoteConstants_compare_HebrewC obj = (BRequest_RemoteConstants_compare_HebrewC)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bout.writeObj(obj.ALEPH, false, null);
		bout.writeObj(obj.BETH, false, null);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_RemoteConstants_compare_HebrewC obj = (BRequest_RemoteConstants_compare_HebrewC)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemoteConstants_compare_HebrewC()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.ALEPH = (byps.test.api.cons.HebrewZ)bin.readObj(false, null);
		obj.BETH = (byps.test.api.cons.HebrewZ)bin.readObj(false, null);
		
		return obj;
	}
	
}
