package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemoteConstants_compare_AllTypesC
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=17

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_1609344203 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_1609344203();
	
	public BSerializer_1609344203() {
		super(1609344203);
	}
	
	public BSerializer_1609344203(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_RemoteConstants_compare_AllTypesC obj = (BRequest_RemoteConstants_compare_AllTypesC)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putBoolean(obj.bool1s);
		bbuf.putBoolean(obj.bool2s);
		bbuf.putChar(obj.char1s);
		bbuf.putChar(obj.char2s);
		bbuf.putDouble(obj.double1s);
		bbuf.putFloat(obj.float1s);
		bbuf.putInt(obj.int1s);
		bbuf.putLong(obj.long1s);
		bbuf.putShort(obj.short1s);
		bbuf.putString(obj.string1s);
		bbuf.putString(obj.stringNull);
		bout.writeObj(obj.ALL, false, null);
		bout.writeObj(obj.arrAll, false, byps.test.api.BSerializer_81775365.instance);
		bout.writeObj(obj.arrInt, false, byps.test.api.BSerializer_100361105.instance);
		bout.writeObj(obj.arrInt4, false, byps.test.api.BSerializer_39910537.instance);
		bout.writeObj(obj.arrStrings, true, byps.test.api.BSerializer_1888107655.instance);
		bout.writeObj(obj.arrStrings4, true, byps.test.api.BSerializer_588723219.instance);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_RemoteConstants_compare_AllTypesC obj = (BRequest_RemoteConstants_compare_AllTypesC)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemoteConstants_compare_AllTypesC()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.bool1s = bbuf.getBoolean();
		obj.bool2s = bbuf.getBoolean();
		obj.char1s = bbuf.getChar();
		obj.char2s = bbuf.getChar();
		obj.double1s = bbuf.getDouble();
		obj.float1s = bbuf.getFloat();
		obj.int1s = bbuf.getInt();
		obj.long1s = bbuf.getLong();
		obj.short1s = bbuf.getShort();
		obj.string1s = bbuf.getString();
		obj.stringNull = bbuf.getString();
		obj.ALL = (byps.test.api.cons.AllTypesZ)bin.readObj(false, null);
		obj.arrAll = (byps.test.api.cons.AllTypesZ[][])bin.readObj(false, byps.test.api.BSerializer_81775365.instance);
		obj.arrInt = (int[])bin.readObj(false, byps.test.api.BSerializer_100361105.instance);
		obj.arrInt4 = (int[][][][])bin.readObj(false, byps.test.api.BSerializer_39910537.instance);
		obj.arrStrings = (java.lang.String[])bin.readObj(true, byps.test.api.BSerializer_1888107655.instance);
		obj.arrStrings4 = (java.lang.String[][][][])bin.readObj(true, byps.test.api.BSerializer_588723219.instance);
		
		return obj;
	}
	
}
