package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BRequest_RemoteWithAuthentication_setReloginCount
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStruct DO NOT MODIFY.
 */

import byps.*;

// DEBUG
// isEnum=false
// isFinal=true
// isInline=false
// #members=1

// checkpoint byps.gen.j.GenSerStruct:274
@SuppressWarnings("all")
public class BSerializer_802968058 extends BSerializer {
	
	public final static BSerializer instance = new BSerializer_802968058();
	
	public BSerializer_802968058() {
		super(802968058);
	}
	
	public BSerializer_802968058(int typeId) {
		super(typeId);
	}
	
	
	@Override
	public void write(final Object obj1, final BOutput bout1, final long version) throws BException {
		final BRequest_RemoteWithAuthentication_setReloginCount obj = (BRequest_RemoteWithAuthentication_setReloginCount)obj1;		
		final BOutputBin bout = (BOutputBin)bout1;
		final BBufferBin bbuf = bout.bbuf;
		bbuf.putInt(obj.count);
	}
	
	@Override
	public Object read(final Object obj1, final BInput bin1, final long version) throws BException {
		final BInputBin bin = (BInputBin)bin1;
		final BRequest_RemoteWithAuthentication_setReloginCount obj = (BRequest_RemoteWithAuthentication_setReloginCount)(obj1 != null ? obj1 : bin.onObjectCreated(new BRequest_RemoteWithAuthentication_setReloginCount()));
		
		final BBufferBin bbuf = bin.bbuf;
		
		obj.count = bbuf.getInt();
		
		return obj;
	}
	
}
