package byps.test.api.remote;

/*
 * Serializer for byps.test.api.remote.BStub_RemoteArrayTypes4dim
 * 
 * THIS FILE HAS BEEN GENERATED BY class byps.gen.j.GenSerStub DO NOT MODIFY.
 */

import byps.*;
@SuppressWarnings("all")
public class BSerializer_1176051258 extends BSerializer_16 {
	
	public final static BSerializer instance = new BSerializer_1176051258();
	
	public BSerializer_1176051258() {
		super(1176051258);
	}
	
	@Override
	public BRemote internalCreate(final BTransport transport) throws BException {
		return new BStub_RemoteArrayTypes4dim(transport);
	}
	
}
